### ISSUE TITLE
Crashing because of certain mods

### ISSUE THREAD

**Issue by Chileeee** [Toma1O6/Guns-RPG#15]
latest.log)Im trying to play the mod with other mods. Every time i try to load it up it crashes. I believe it is because of mods that require GeckoLib. Whenever play this mod without GeckoLib it runs just fine
[latest.log](https://github.com/Toma1O6/Guns-RPG/files/9185511/latest.log)
.

**Comment by Toma1O6** [comment]
The issue is caused by geckolib attempting to load our animations which are not compatible with geckolib. I suggest you to raise issue in geckolib to ignore animations from other mods
