### ISSUE TITLE
MC crashes while using find me on guns rpg

### ISSUE THREAD

**Issue by hansonsofan** [Toma1O6/Guns-RPG#23]
Hi, the game crashed while using find me and I think it was related to guns RPG mod. This error pops up

The game crashed whilst exception in server tick loop
Error: java.lang.AbstractMethodError: Method dev/toma/gunsrpg/common/tileentity/SmithingTableTileEntity.func_191420_l()Z is abstract

Exit code:-1

This happens while using find me while crafting and finding the ingredients used on the JEI. But strangely It happened while using find me on other items.

[crash-2023-02-05_11.54.47-server.txt](https://github.com/Toma1O6/Guns-RPG/files/10610255/crash-2023-02-05_11.54.47-server.txt)

**Comment by Toma1O6** [comment]
Hi, this is actually weird issue which in my opinion should not happen at all, as this is compile time error. I will try to fix it for the next update, but I don't guarantee anything
