### ISSUE TITLE
(1.16.5) GunsRPG + Astral Sorcery Crash on world loading

### ISSUE THREAD

**Issue by ItzYerRob** [Toma1O6/Guns-RPG#24]
Seems like GunsRPG 1.2.5 and Astral Sorcery (Even the latest version which apparently reverts mixins back to JS ASM) do not work together, giving out a warning about failure to load datapacks that then end in a crash even in safe mode, whereas removing either of them will result in a successful world load without issues.

This is on a pack with quite a few mods though, of note the performance enhancing ones like Rubidium, Magnesium Extras, Oculus, FerriteCore

[latest.log](https://github.com/Toma1O6/Guns-RPG/files/10861739/latest.log)
[debug.log](https://github.com/Toma1O6/Guns-RPG/files/10861809/debug.log)

**Comment by Toma1O6** [comment]
I'd suggest to create issue on Astral Sorcery github.
Cause of this is that we use `perks` data directory with 2 completely different perk data structures so neither of these 2 mods can load all data.
On our side all json errors are handled by skipping loading and just logging error. I'd suggest to do the same
