### ISSUE TITLE
Guns don't work when modifying bloodmoon config (1.16.5)

### ISSUE THREAD

**Issue by TheEffortFighter** [Toma1O6/Guns-RPG#25]
https://user-images.githubusercontent.com/82852195/224506626-f1a165dd-a514-417b-bffc-4ee1b802af39.mov

All details are shown in the video

By the way, I did try it where I only modified the blood moon config and this still happened, the sleep restriction has nothing to do with it.

**Comment by Toma1O6** [comment]
I have pushed fix to curseforge - version 1.2.7. It should be available soon
