### ISSUE TITLE
Could you add a hold to ADS to the configs? (suggestion) (1.16.5)

### ISSUE THREAD

**Issue by TheEffortFighter** [Toma1O6/Guns-RPG#26]
What the title says basically, feels a little weird to have toggle aim, and I did try and search the configs for something to change it the way you ADS, but I couldn't find it, so I'm assuming it isn't currently implemented in the mod, but if it is I apologize.

**Comment by Toma1O6** [comment]
Feature is implemented since 1.2.10 version
