### ISSUE TITLE
Crash when handling knock back

### ISSUE THREAD

**Issue by TaoismDeepLake** [Toma1O6/Guns-RPG#29]
[minecraft-exported-crash-info-2023-04-03T12-40-35 (1).zip](https://github.com/Toma1O6/Guns-RPG/files/11156263/minecraft-exported-crash-info-2023-04-03T12-40-35.1.zip)

I found this in a Chinese MC community, original link https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=13437&page=1#pid62219

A player reported that your gun mod conflicts with other gun mods like TaC (https://github.com/ClumsyAlien/TimelessandClassics_Reforged)

It seems that something is wrong with the mixins, especially on non-living entities(like bullets) causing knockbacks. Please check if there is anything you can do. Thank you.

**Comment by Toma1O6** [comment]
This issue is fixed in version 1.2.9 which is currently being uploaded to curseforge
