### ISSUE TITLE
Kills not registering for circle missions

### ISSUE THREAD

**Issue by ShurikenBlade** [Toma1O6/Guns-RPG#30]
The missions where you must stay in a circle and kill certain enemies is not counting the kills.

**Comment by Toma1O6** [comment]
Does it happen to all quests or only specific ones?
I'm going to need information about which quest exactly caused this issue and which extra conditions you had.

**Comment by ShurikenBlade** [comment]
Any quest that you have to go to a certain location, to start and stay in a circle and fight enemies. If it's headshots only, or just a regular elimination quest the kills are not registering

**Comment by Toma1O6** [comment]
Which version of gunsrpg are you using?

**Comment by ShurikenBlade** [comment]
I think it is gunsrpg-1.16.5-1.2.10

**Comment by Toma1O6** [comment]
You can try version 1.3.0 to see if that helps, however in my opinion there will be some mod conflict probably. If updating to the newest version does not help, then please provide list of all mods which you are using (modpack file would be best, but I will manage with modlist)
